# Generated by Django 4.1.5 on 2023-01-05 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transactionid",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("category", models.CharField(max_length=100)),
                ("expensename", models.CharField(max_length=100)),
                ("cost", models.CharField(max_length=100)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
